on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

name: Test
jobs:
  ci:
    name: Test for Golang ${{ matrix.go-version }} on ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: [ 1.21.x, 1.22.x, 1.23.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run Test
        run: go test ./... -v -race